# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-PathInfo-Ext
version:      1.22
version_from: lib/File/PathInfo/Ext.pm
installdirs:  site
requires:
    Carp:                          1
    Cwd:                           3
    Digest::MD5:                   2
    File::Copy:                    2
    File::Path:                    1
    File::PathInfo:                1
    File::Type:                    0
    Test::Simple:                  0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
