# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-PathInfo-Ext
version:      1.13
version_from: lib/File/PathInfo/Ext.pm
installdirs:  site
requires:
    File::Path:                    0
    File::PathInfo:                1.12
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
